import Head from "next/head";
import Header from "./Header";
import Footer from "./Footer";

export default function ContentWrapper({ children, title }) {
  const fullTitle = title ? `Top Fives - ${title}` : "Top Fives";
  return (
    <div>
      <Head>
        <title>{fullTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Footer />
    </div>
  );
}
